add readme
thetribeio/html-to-pdf pull request #12
Opened 2022-08-25 08:35 UTC by SetiZ

2022-08-25 09:29 UTC, jvasseur requested changes

2022-08-25 09:29 UTC, jvasseur commented on README.md
> +You then will be able to make a `POST` request to `localhost:3000` with plain text data and the response will generate a pdf for you.
```suggestion
You then will be able to make a `POST` request to `localhost:3000` with HTML data and the response will generate a pdf for you.
```

2022-08-25 13:18 UTC, jvasseur requested changes

2022-08-25 13:18 UTC, jvasseur commented on README.md
> +# html-t-pdf
```suggestion
# html-to-pdf
```

2022-08-25 13:25 UTC, SetiZ commented on README.md
> +# html-t-pdf
rooh la boulette

2022-08-25 13:32 UTC, jvasseur requested changes
Sorry for not catching everything on the first review

2022-08-25 13:32 UTC, jvasseur commented on README.md
> +this is a api that can be used to generate a pdf from a source file.
```suggestion
this is an API that can be used to generate a PDF from a source file.
```

2022-08-25 13:32 UTC, jvasseur commented on README.md
> +You then will be able to make a `POST` request to `localhost:3000` with HTML data and the response will generate a pdf for you.
```suggestion
You then will be able to make a `POST` request to `localhost:3000` with HTML data and the response will generate a PDF for you.
```

2022-08-29 09:32 UTC, jvasseur approved these changes

2022-08-29 09:32 UTC, merged